### ISSUE TITLE
Weird symbols with R prompt output (NeoVim)

### ISSUE THREAD

**Issue by KKPMW** [metakirby5/codi.vim#10]
Attaching a screenshot of the output I get when using Codi with R on NeoVim.

Tried haskell and python - both worked fine.

![screen shot 2016-08-15 at 02 16 15](https://cloud.githubusercontent.com/assets/7273684/17652763/6494b7b2-628e-11e6-8b5d-a21fb4a83007.png)

**Comment by ZweiSpeedruns** [comment]
I haven't seen the R interpreter, but seeing as 200 (the correct answer) is buried in there along side timestamps, I'm going to take a stab in the dark and guess that the default regex for the R interpreter prompt is incorrect.

**Comment by metakirby5** [comment]
The main issue is that there's no preprocess to strip out control characters and add newlines. What's the version of the R interpreter you're using?

**Comment by KKPMW** [comment]
R version 3.3.0 (2016-05-03) -- "Supposedly Educational".

You said it works on your end, so that's a bit weird to me. Did you use NVim? I tried running it with fresh vimrc and without tmux, still the same.

**Comment by metakirby5** [comment]
Using it with vanilla Vim - will test with NVim when I get the chance, but I suspect that the R version is the culprit here.

**Comment by KKPMW** [comment]
Hmm the only newer version is 3.3.1. I read their release notes and they didn't mention anything about control characters. But I will try updating later today to see if this helps.

Or maybe you were using an older version?

**Comment by metakirby5** [comment]
Hmm... It would actually be really useful if I had the exact characters. Can you enter the below into the main buffer, switch to the codi buffer, write it, and upload the file somewhere? Copy and pasting doesnt help too much because they use literal <ESC> characters that aren't printable.

```
55555
66666
77777
"Hello World"
88888
```

**Comment by KKPMW** [comment]
OK I solved the problem, sorry to keep you needlessly occupied.

The issue was - I was using "colorout" library for R and it was written in my .Rprofile. So R prompt output was being colored.

But as I was checking this another issue appeared - in R codi prints sort(9:1), but returns blank for sort(10:1).

**Comment by metakirby5** [comment]
Ah, I know exactly why that second issue is happening - will put up a fix soon.

In the meantime, could you still upload your output with `colourout` enabled? I'd like to make it compatible with that, since it doesn't seem like too much trouble.

**Comment by metakirby5** [comment]
Closing this for now, since the sort(10:1) issue has been fixed. if color output compatibility becomes a priority again, please open another issue 🙂
