### ISSUE TITLE
[Proposal] Pass environment variables to default interpreters

### ISSUE THREAD

**Issue by hristost** [metakirby5/codi.vim#102]
As we already know, codi.vim does not always work out of the box due to `.inputrc` configurations that take control over `c-j`. For example:
```
#.inputrc
set editing-mode vi
set show-mode-in-prompt on
set keyseq-timeout 0
```
This stops interpreters that rely on `readline` (think python) from working. It would be nice if we can use a custom `.inputrc` whenever running codi, so users don't have to modify their existing configurations. This can be easily achieved by setting the [`INPUTRC`](http://man7.org/linux/man-pages/man3/readline.3.html#INITIALIZATION_FILE) environment variable when running the interpreter.

## Proposal
Introduce a variable with environment flags to get passed to the interpreter, for example:
```
let g:codi#environment_flags = "INPUTRC=/dev/null"
```

**Comment by hristost** [comment]
Furthermore, I'd advocate for defaulting to an empty `.inputrc`, but I haven't done research on what side-effects this could have.

**Comment by Konfekt** [comment]
This proposal can probably be closed as the above commits implement it.

**Comment by hristost** [comment]
Works for me! Thanks for implementing this
