### ISSUE TITLE
You know what would be cool? vim interpretor support

### ISSUE THREAD

**Issue by grepsuzette** [metakirby5/codi.vim#105]
Not a bug. 

Codi is so cool.
And on the other hand, using vim command line or wincmd (q;)  is not that practical. 

I was wondering if there was a way to have a vim interpreter loop similar to all those interpreters with which Codi works but for vim script. Then we could have vim support for Codi and it would be really fun. 

Unfortunately I don't know if that would possible, but I thought that discussion ought to be started.

**Comment by metakirby5** [comment]
Thanks for the kind compliment!

It seems doable as long as Vim exposes a way to run as an interpreter - perhaps [here](https://vim.fandom.com/wiki/Vim_as_a_system_interpreter_for_vimscript) is a good place to start.
