### ISSUE TITLE
Neovim alignment error

### ISSUE THREAD

**Issue by epeery** [metakirby5/codi.vim#106]
## Neovim alignment error
- **Brief description:** Output becomes misaligned when file gets too long
- **Expected results:** Maintain alignment in Neovim
- **Actual results:** Once the file becomes long enough to justify scrolling, output is printed ~10 lines lower than actual code

Issue still occurs with a totally blank vimrc

## Steps to reproduce
* `$ vim index.js`
* Press Enter a bunch or just type a lot of code

[![asciicast](https://asciinema.org/a/232388.svg)](https://asciinema.org/a/232388)

## Environment
- Operating system: Arch Linux
- Version of `script`: util-linux                        June 2014                         SCRIPT(1)
- https://pastebin.com/BrsQx4JJ
- https://filebin.ca/4ZQwqyS7t7a6/codi-log.txt

Thanks in advance!

**Comment by lukelbd** [comment]
@epeery Why did you close this? Found a workaround? Having the same issue in vim 8.X.

**Comment by lukelbd** [comment]
I submitted a PR in #145 that may fix this issue.
