### ISSUE TITLE
Screencast link is broken

### ISSUE THREAD

**Issue by slavaGanzin** [metakirby5/codi.vim#113]
Hello

Screencast link in readme is broken:
```md
For more information, check out the [documentation](doc/codi.txt).
Watch a [screencast](https://ptpb.pw/t/~codi)!
```

```bash
curl "https://ptpb.pw/t/~codi"
>>> curl: (6) Could not resolve host: ptpb.pw
```

Maybe host it on [asciinema](https://asciinema.org/)?

**Comment by metakirby5** [comment]
I have unfortunately forgotten what the contents of the screencast even was 😅 I do have an issue open to [record a new screencast](https://github.com/metakirby5/codi.vim/issues/12), but I just haven't had the chance to.
