### ISSUE TITLE
Codi does not update

### ISSUE THREAD

**Issue by timonson** [metakirby5/codi.vim#115]
## Issue description

All Codi commands are 'reacting' but it doesn't update. In other words, there is no 'output'. It seems to be similar to these issues:
- https://github.com/metakirby5/codi.vim/issues/70 
- https://github.com/metakirby5/codi.vim/issues/62

I tested it with python and javascript and tried a lot of different ways/commands to make codi update.

The /tmp/cmd file is created and executable. After trying it with javascript it contains:  
`node' '-e' 'require("repl").start({ignoreUndefined: true, useGlobal: true})`

I use the newest vim and codi versions on arch linux. 

#### Example

![2019-09-05T02:25:10+02:00_487x219](https://user-images.githubusercontent.com/54777088/64302673-a9a05300-cf84-11e9-82ff-4822cbb8f337.gif)

**Comment by medeirosjoaquim** [comment]
Tried with vim 8.1 (with +job and channel) on  Debian. Happens the same thing, no output but only for javascript. Python works fine.

**Comment by timonson** [comment]
@medeirosjoaquim I am using an older Codi version, I believe I picked a random one from 2018 and it works there. But it is obviously not optimal and I was not able to figure out which later commit has caused this bug.

**Comment by timonson** [comment]
Your last changes seem to have fixed this issue @metakirby5
