### ISSUE TITLE
Slightly tangential suggestion -- add Codi's display as part of LSP plugins like coc.nvim

### ISSUE THREAD

**Issue by lanza** [metakirby5/codi.vim#127]
So codi.vim has by far the best display technique for errors/diagnostics that I've seen across all plugins. The right alignment and having the information in a different buffer is just a drastically superior approach compared to virtual text, popovers or status bar messages.

I'd LOVE to see this technique expanded to be a general purpose diagnostic display buffer tool that's usable via LSP clients such as coc.nvim. Have you thought about this?

**Comment by metakirby5** [comment]
Unfortunately, the implementation I did for codi.vim is quite closely coupled and not built for general use. At the moment, I don't have the bandwidth to extract the right-aligned separate buffer functionality into a ready-to-use library. That said, there's no reason why other tools can't use a similar technique 🙂 

Thank you for the kind compliments!
