### ISSUE TITLE
ghci output filtering/processing issues

### ISSUE THREAD

**Issue by dkasak** [metakirby5/codi.vim#13]
I'm seeing two issues with filtering/processing output from ghci:

* Codi outputs `Loaded GHCi configuration from /home/dkasak/.ghci` in the very first line of its output which is a line ghci prints out at startup.
* The standard prompt in ghci changes when you import additional Haskell modules to reflect this so the prompt isn't always just `Prelude> ` but can be e.g. `Prelude Control.Monad> `. Furthermore, there is a different prompt for continuation lines which is printed when you start a block (for instance, an if-then-else expression after you've entered `if expr<ENTER>`). This prompt exchanges `>` with `|`.

An example session:

```
GHCi, version 8.0.1: http://www.haskell.org/ghc/  :? for help
Loaded GHCi configuration from /home/dkasak/.ghci
Prelude> let a = 3
Prelude| 
Prelude> if a > 2
Prelude| then a + 1
Prelude| else 42
4
Prelude> import Control.Monad
Prelude Control.Monad> if a == 3
Prelude Control.Monad| then [1, 2, 3]
Prelude Control.Monad| else []
[1,2,3]
```

Regarding the second problem, I think it would be better to simply consider everything up to (and including) a `>` or `|` character to be the prompt, by default.

**Comment by metakirby5** [comment]
Is it guaranteed that there will be no `|` or `>` characters in anywhere but the prompt? If not, I will probably have to keep "Prelude" in the regex.

**Comment by metakirby5** [comment]
Very easy fix if I just keep "Prelude" in the regex; I suppose users with custom prompts will just have to update their Codi settings.

![](https://www.dropbox.com/s/or2kfuzbrj78y2e/Screenshot%202016-08-16%2000.39.26.png?dl=1)

Thank you for the contribution!

**Comment by dkasak** [comment]
> Is it guaranteed that there will be no | or > characters in anywhere but the prompt? If not, I will probably have to keep "Prelude" in the regex.

No, but it should be the case that everything up to the *first* `>` or `|` is the prompt, so you could use an eager (non-greedy) match.

> Very easy fix if I just keep "Prelude" in the regex; I suppose users with custom prompts will just have to update their Codi settings.

The problem is not with custom prompts but with the fact that Prelude is itself a module, just one that is loaded implicitly, but this behaviour can be disabled or exchanged with a different kind of prelude in `$HOME/.ghci`. I believe a non-greedy match would be a more accurate fix for this reason, but this can be lived with, albeit at a slight decrease in comfort.

Thanks for your work on this!

**Comment by metakirby5** [comment]
Hmm, are you sure about everything up to the first `>` being a prompt? I see errors like `<interactive>...` being a counterexample, which is why I decided to just push up the change with Prelude in the prompt.

In any case, if you can provide a better regex and submit a pull request, I will gladly take a look and merge it in :) I'm by no means an expert in Haskell, but I dabbled in it a little once so I thought it would be cool to add support for it.

**Comment by dkasak** [comment]
Hmm, I think you're right, I wasn't taking errors into account. I'll think about it some more and try to work on it when I catch some time.

That said, I'm still having a problem with the `Loaded GHCi configuration from /home/dkasak/.ghci` line. You're probably not seeing it because it's only displayed if the file exists (which is the case if you have any kind of custom ghci configuration, regardless of whether it's changing the prompt or not). Would you mind reopening this until I've tried fixing it myself?

**Comment by dkasak** [comment]
Also, it might be worth it to run ghci with `-ignore-dot-ghci` from Codi, for the time being at least. That will make it ignore any custom user configuration which might even be the sane thing to do in the long run, depending on how hard it is to fix all those special cases.

**Comment by metakirby5** [comment]
Sounds good! Will we be forfeiting continuation lines, though? I had to `:set +m` to get those.

It's curious that you're still getting the `Loaded GHCi...` line, though, as I can't seem to reproduce it on my Mac machine or Ubuntu VM. The immediate cause I can think of is misplaced prompts. Would you mind posting the contents of the Codi pane when you set `g:codi#raw = 1` and `g:codi#rightalign = 0`?

**Comment by dkasak** [comment]
Yes, we'll lose continuation lines. Though I suppose many people don't have them turned on in their `.ghci` file either so it might be reasonable to add an additional parameter to Codi to specify commands that should be run to initialize the interpreter (probably as a list of vimscript strings) when it's first started. Would you be open to this? It seems like a nice addition as it would facilitate getting the interpreter into a known default state (so things don't get too crazy) and it would probably be useful for other interpreters as well.

Regarding the other problem, I'll post an example raw Codi session soon.

**Comment by metakirby5** [comment]
Hmm, I have somewhat mixed feelings about startup strings. I want to keep as little language-specific configuration as possible in Codi; after all, it's what made it so easy for me to add support to so many languages, may of which I only have a surface-level understanding of. It also introduces the potential issue of unforeseen side-effects, e.g. if a user expects continuation lines since they are set in their `.ghci`, but does not get them. I think if a reasonable amount of languages require this feature it's worth pursuing. However, since this only applies to Haskell at the moment (and for a non-vital feature), I'd like to refrain from adding this parameter for now.

On second thought, for the unforeseen side-effects reason I mentioned above, I'm having second thoughts about `-ignore-dot-ghci`. I think a good compromise would be to generalize the regex to a reasonable feature set (e.g. with continuation lines, but no support for customized prompts). What are your thoughts?

**Comment by dkasak** [comment]
I agree you should probably wait with adding startup strings until at least a few more people try playing with the Haskell backend and/or the need arises for other languages. I'm not sure how useful the Haskell backend is in its present form since I haven't yet managed to get it to get into a state where I can experiment with it. I think ghci is sufficiently different from most other language interpreters that it might require a bit of special treatment to be truly useful. 

Also, since Haskell is such a flexible language, I fear custom ghci settings might too easily break Codi, whatever defaults you choose to expect. This would unnecessarily break the out-of-the-box experience. This is why I thought that putting it into a default vanilla state with `-ignore-dot-ghci` might be most useful by default and then users which don't like this could override it themselves. I can see the merit in your position too, though.

However, for this to be even remotely useful, a user has to be able to input stuff that spans multiple lines (for instance, new data definitions, since those would be terribly cumbersome on one line). ghci implements this using the `:{` and `:}` commands which delimit multiline blocks like this:

```
:{
data Foo = Bar
         | Baz
         deriving Show
:}
```

Codi seems to barf on `:{` though. I'll include the output for that when I post that raw log.

**Comment by dkasak** [comment]
Okay, so I started vim with `/usr/bin/vim -c 'let g:codi#raw = 1 | let g:codi#rightalign = 0'`.

Then I typed

```
let a = 42

a + 1

```

And the output is the following

```
let a = 42
a + 1
    
Prelude> 
ghc: signal: 15
Leaving GHCi.
Session terminated.
GHCi, version 8.0.1: http://www.haskell.org/ghc/  :? for help
Loaded GHCi configuration from /home/dkasak/.ghci
Prelude> let a = 42
Prelude| 
Prelude> a + 1
43
Prelude>     
Prelude> 
```

**Comment by metakirby5** [comment]
I can't seem to find your `:{` example posted, could you point me to where it is?

Also, thanks to your log, I think I've pinpointed the reason for the `Loaded GHCi configuration...` issue you were facing. It looks like there is an extra `Prelude>` prompt before the interpreter actually processes the input. Codi works by ignoring all input up until the first prompt, and treating all prompts after it as corresponding to each line in the buffer. Would you have any idea as to why that extra prompt shows up on your setup, but not mine? Perhaps try running `ghci` without any configuration?

**Comment by dkasak** [comment]
Uh, sorry, I forgot to post it apparently. :dancer: 

Source:

```
:{
data Foo = Bar
         | Baz
         deriving Show
:}

Baz

```
Session terminated.
:b
GHCi, version 8.0.1: http://www.haskell.org/ghc/  :? for help
Loaded GHCi configuration from /home/dkasak/.ghci
Prelude> :b
The break command requires at least one argument.
Prelude> 
```

No idea as to why the extra prompt shows. I'll try running without any configuration when I get home. Though, shouldn't empty prompts simply get ignored regardless, since empty lines in the file seem to work as if you pressed return in the interpreter (which evokes an empty prompt)?

**Comment by dkasak** [comment]
The extra prompt isn't actually printed if I run ghci by itself. What seems to be tripping Codi up is multiline support, so if I have `:set +m` in my `.ghci`, I get the `Loaded GHCi...` line and the output seems broken in several small ways. If I remove `:set +m`, the line disappears and basic things work as expected.

Those `:{ ... :}` blocks still don't work, though.

**Comment by metakirby5** [comment]
Odd, it seems to be working for me...

![](https://www.dropbox.com/s/dbye6hu7bhcfrr9/Screenshot%202016-08-16%2021.25.58.png?dl=1)

I also have enabled multi-line since you told me about it. If the issue persists even without any configuration, please update me. I will likely have to defer the issue until after a refactor I'm planning, which will include debug logging so I can take a better look at the issue.

**Comment by oblitum** [comment]
I'm only getting the first line of error message, which is not much useful, for example, in `ghci` I have:

```
Prelude Prelude.Unicode
λ "abc" `union` "def"

<interactive>:1:7: error:
    Variable not in scope: union :: [Char] -> [Char] -> t
```

Codi only shows "<interactive>:1:7: error:".
