### ISSUE TITLE
jq support?

### ISSUE THREAD

**Issue by alok** [metakirby5/codi.vim#134]
jq is a full language, and having the ability to eval json live and print it out would be amazing.

**Comment by metakirby5** [comment]
A small issue is that there are two inputs: the JSON to process and the jq expression to evaluate. We'd probably have to add some sort of argument handling for specifying the input JSON, as I'm assuming the input you want to actively work on is the jq expression.

A simple workaround is using your language of choice which has a jq library, and writing your script as a string in that. An example is below.

![image](https://user-images.githubusercontent.com/3402603/115418480-79c6c180-a234-11eb-9083-b8061b9a5534.png)
