### ISSUE TITLE
Codi doesn't work with other plugins that use extmark.

### ISSUE THREAD

**Issue by rhcher** [metakirby5/codi.vim#142]
## Issue description
- Brief description
Codi doesn't work with other plugins that use extmark because codi will clear all namespace, see [here](https://github.com/dcampos/nvim-snippy/issues/48) for details.
- Expected results
Codi.vim work together with other plugin that use extmark.
- Actual results
Codi.vim doesn't work with other plugin that use extmark.
- A minimal `.vimrc` that will reproduce the issue
```vim
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'dcampos/nvim-snippy'
Plug 'honza/vim-snippets'
Plug 'metakirby5/codi.vim'
call plug#end()
PlugInstall | quit

imap <expr> <Tab> snippy#can_expand_or_advance() ? '<Plug>(snippy-expand-or-advance)' : '<Tab>'
imap <expr> <S-Tab> snippy#can_jump(-1) ? '<Plug>(snippy-previous)' : '<S-Tab>'
smap <expr> <Tab> snippy#can_jump(1) ? '<Plug>(snippy-next)' : '<Tab>'
smap <expr> <S-Tab> snippy#can_jump(-1) ? '<Plug>(snippy-previous)' : '<S-Tab>'
xmap <Tab> <Plug>(snippy-cut-text)

lua << EOF
    require('snippy').setup({
        hl_group = 'Search',
    })
EOF
```
- Exact steps to reproduce the issue, starting with the command used to open
  `vim`
  1. `nvim -u mini.vim test.py`
  2. run command `:Codi`
  3. input `def` and press `tab` to expand snippet, then input random, the error message pop up
- Any relevant screenshots
![image](https://user-images.githubusercontent.com/50723480/150717885-bfe999dc-eae0-4487-80c8-0f64162424ae.png)
- If it's not too much trouble, a screencast (e.g. asciinema) of the issue

## Environment
- Operating system
wsl2 Arch
- Version of `script` (if you don't know, just paste the last line of the
  man page)
- The following **in a pastebin**, to reduce visual clutter:
  - Entire output of `nvim --version`
  ```   
  NVIM v0.7.0-dev+920-g7e2ce35e3b
  ```
  - Log lines (see `:h g:codi#log`)

**Comment by metakirby5** [comment]
I don't have the bandwidth to make a fix right now, but if someone can try the [proposed fix](https://github.com/dcampos/nvim-snippy/issues/48#issuecomment-1019578870), run some tests, and submit a pull request, I'm happy to review!

**Comment by JoseConseco** [comment]
I think this https://github.com/metakirby5/codi.vim/pull/151 PR should fix the issue.
