### ISSUE TITLE
Screencast doesn't work

### ISSUE THREAD

**Issue by JESii** [metakirby5/codi.vim#154]
If you only have a quick question, consider posting it on the Gitter.

Otherwise, please include the following:

## Issue description
Went to see the screencast which is part of the description here.
Expected to see the screencast
Instead bot this:
![2022-08-14 at 8 10 PM](https://user-images.githubusercontent.com/486/184571062-1cf5e826-6f65-4697-a36d-7d208f8dfe82.jpg)

## Environment
chrome browser using the link from the github account

**Comment by metakirby5** [comment]
Oops, thanks! Just removed it from the readme, since I unfortunately didn't keep a backup.
