### ISSUE TITLE
Startup errors and very slow evaluation on macOS [needs a check for Vim 7.4]

### ISSUE THREAD

**Issue by kedean** [metakirby5/codi.vim#23]
Installed with vim-plug and ran using OSX El Capitan (10.11.6). Running ":Codi python" from vim results in the following errors for a short time, then the plugin loads:
```
Error detected while processing /Users/kedean/.vim/plugged/codi.vim/autoload/codi.vim
line 119:
E216: No such group or event: QuitPre * call s:codi_autoclose()
```

Once the plugin loads, evaluation is extremely slow. Evaluating just `"foobar"` takes around 5 or 6 seconds. This happens with the default python-2.7.10 that comes with El Capitan and with python-3.5.2 from Homebrew.

**Comment by metakirby5** [comment]
The lack of a QuitPre auto command leads me to believe that you have an older version of vim. Do you have at least 7.4?

**Comment by iovis9** [comment]
Running on El Capitan here and it works flawlessly with no noticeable lag. Is it Homebrew's vim or the default OS X one?

**Comment by kedean** [comment]
Looks like El Capitan comes with 7.3 by default. Installing 7.4 from Homebrew fixed the issue!

**Comment by metakirby5** [comment]
Good to hear! I need to put a check for Vim 7.4 in, so I'm leaving this issue open until I do.
