### ISSUE TITLE
Question about user-defined interpreters

### ISSUE THREAD

**Issue by still-dreaming-1** [metakirby5/codi.vim#26]
According to the documentation, `g:codi#interpreters` is a dictionary of user defined interpreters. It also says it will not erase the internal default interpreters. Does this mean there is currently no supported way of customizing how the built in interpreters work? As in If I make my own javascript interpreter, it will have no effect because it will not overwrite the built in one? The reason I ask is I want to change the way node is started to pass a custom parameter to it. Passing to node the name of a .js file which creates it's own REPL object is a standard way of writing your own REPL in node which is needed in order to bring variables into context at the start of the REPL session. This feature will be used by anyone who uses my [living-tests](https://github.com/still-dreaming-1/living-tests) node testing framework, which will also rely on codi to work. Thanks for the help and this awesome plugin!

**Comment by still-dreaming-1** [comment]
I just realized I should be able to get my testing framework to work without that feature, it will just require a little extra code at to be added to the top of each test file. Anyway this is still a question I have, just wanted to mention that.

**Comment by metakirby5** [comment]
Sorry for the unclear documentation - you are in fact able to override the default interpreters. What I wanted to mean was if you define your own interpreters,  you'll still be able to use the defaults. Also, the definitions are deeply updated, so if all you want to change is the bin, the default prompt regex is still applied. I'll leave this open until I fix up the documentation. If you have any suggestions for a better way to phrase things, please let me know :)

**Comment by still-dreaming-1** [comment]
Thanks for the help. Is changing the bin the best way to pass parameters to the REPL?

**Comment by metakirby5** [comment]
Yes. It wouldn't be great to override the default Codi behavior for all javascript files though, so I suggest making a custom filetype for living-tests like `jslt` or something, so you can set the interpreter settings for only living-tests files.

**Comment by still-dreaming-1** [comment]
What about changing the directory node is started from (not in)? It seems node is started from whatever directory is the current working directory in Vim. This makes sense in a way, but it creates some problems. If the code in the script needs to require another file, it makes it hard to know what the correct path is. In node, if the code that was running was required from another place, then the path of any require statements can just be relative to the path of the current file. Therefore I think it would be a better default behavior for codi to start node from the directory that the current buffer file resides in. This would allow the script you are editing to specify require statements relative to the file being edited, which is what Node.js programmers are used to doing. I am not suggesting you customize the way the REPL behavior to be different from normal, just that it should be started from the directory of the file being edited.

**Comment by metakirby5** [comment]
As long as there is an option to revert to the original behavior (which is more consistent with Vim in general), I think this is a reasonable default, given the nature of REPLs. Please file a separate issue for this, though :)
