### ISSUE TITLE
Strange behavior in Neovim

### ISSUE THREAD

**Issue by still-dreaming-1** [metakirby5/codi.vim#28]
I thought it was working better in Neovim for me, but that didn't last very long. It is hard to say exactly what does not work right because even the reproduce case that I originally provided is not consistently working to reproduce that issue now. In general after using codi in Neovim for any length of time the behavior of Neovim just becomes generally wonky. I realize that is not exactly a helpful bug report, but I just want to know if other people are using this in Neovim and not having lots of issues? I mean I know if you just start it up and test one little thing in Neovim it might work ok, but if you actually use codi for real world things does it work well for other people? If not, it should not be that difficult to reproduce this behavior. I think I will help try to debug it because I really need it fixed. I'm not sure if I will understand the code enough though. I might want to start with contributing in some smaller way. Anyway, we don't have to talk about that here, I just mentioned that here because I don't want you to feel like I'm just providing non useful bug reports, I am willing to help. We can continue the conversation about contributing elsewhere, you will see a pull request from me soon that will provide more details.

**Comment by metakirby5** [comment]
I think it's better to only file specific issues that have consistently identifiable symptoms, and preferably steps to reproduce. Now that we have a Gitter, we can move discussion like this over there.

P.S. feel free to shoot me an email if you want to talk about things that don't belong in issues nor Gitter.

**Comment by still-dreaming-1** [comment]
I'm not sure that only filing specific issues make sense when the issue is that everything is an issue. I don't know how to quantify that. Perhaps I was wrong about closing the general nvim support issue... Is this working well in Neovim for anybody? I don't mean like you tried it out and it seemed ok, but that you actually use it and it works pretty well?

**Comment by metakirby5** [comment]
I haven't extensively tested in NVim. This is more or less a band-aid solution until I rework things to use Python's pty module + threads, which I think should solve most issues since it will allow me to have a much greater degree of control over the output and asynchronicity.

**Comment by still-dreaming-1** [comment]
So right now I'm learning python so I can help work on this so codi will work better with my favorite editor so I can use codi with my testing framework with that editor so I can debug and test faster while working on a plugin for that editor so I don't have to wait while tags are being generated... XD

**Comment by still-dreaming-1** [comment]
Here is something interesting. In Neovim type `:h provider-python` It says 

> Nvim supports the Vim legacy python-vim and python3 interfaces via              
>external Python interpreters connected via RPC,                                 
>                                                                                
>Note: Only the Vim 7.3 API is supported; bindeval (Vim 7.4) is not.

**Comment by still-dreaming-1** [comment]
It seems to be working great in Neovim for me now, even better than it does in Vim.
