### ISSUE TITLE
Start REPL from the directory of the file being edited

### ISSUE THREAD

**Issue by still-dreaming-1** [metakirby5/codi.vim#30]
It would be helpful for me to have the REPL start from the directory of the file being edited instead of starting it from Vim's current working directory, at least for node. This would allow the script to require() files using a path relative to that file, which is what node programmers normally do. This might be a good default for other REPLs as well, but I am not sure. Perhaps there could be an option for both behaviors.

**Comment by metakirby5** [comment]
Closed with #32.
