### ISSUE TITLE
Codi only displays the last line of the output, which is not always the expected behavior.

### ISSUE THREAD

**Issue by gillescastel** [metakirby5/codi.vim#33]
Problem: Codi only displays the last line of the response.

* * *

Behavior of Codi:

![image](https://cloud.githubusercontent.com/assets/7069691/18129821/b60722f0-6f8c-11e6-9b2c-7a95a967c9e2.png)

Expected behavior:
```python
Python 2.7.12 (default, Jul  1 2016, 15:12:24) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from sympy import *
>>> init_printing()
>>> f, x = symbols('f x')
>>> f = exp(x)
>>> diff(f)
 x
ℯ 
>>> print('a\nb')
a
b
>>> 
```

Minimal test case:

```python
print('a\nb')
```

* * *

Same for javascript:
```javascript
~node
> console.log('test')
test
undefined
> 
```

Using Codi, only the last line, `undefined`, is shown.

How could this be resolved?

Thank you for this great plugin!

**Comment by metakirby5** [comment]
This is something which is being discussed at #27. Due to the line-wise nature of Codi, multi-line output is currently not supported. However, using folds is a possible compromise.

Closing this because of its similarity to #27.
