### ISSUE TITLE
Add hooks for entering/quiting codi "session"

### ISSUE THREAD

**Issue by lervag** [metakirby5/codi.vim#4]
First, I think you are on to something very useful here! Thanks!

I think it would be very convenient to either add some user autocmds or function hooks upon entering and closing a Codi session. This would, for instance, allow to set the `VertSplit` highlighting differently when using codi. I like showing the splits clearly in general, but I can see how the right aligned buffer without visual clutter can be useful for codi.

**Comment by metakirby5** [comment]
Sounds like a good idea! I'll look into user autocmds shortly.

If you're up for it, don't be afraid to submit a pull request :) [s:codi_spawn](https://github.com/metakirby5/codi.vim/blob/b028d47d519288575d889207e6d0a196c5603716/autoload/codi.vim#L428) and [s:codi_kill](https://github.com/metakirby5/codi.vim/blob/b028d47d519288575d889207e6d0a196c5603716/autoload/codi.vim#L233) are good starting points.

**Comment by lervag** [comment]
Thanks, nice work! It seems, though, that the Leave autocmds are not fired if I do `Codi!` or `Codi!!`. I've tried to e.g. just set `g:test = 1` with `au User CodiLeavePre let g:test=1`, but this is never set.

I'm remember that I myself have had some minor issues using the `BufWinLeave` autocmd. Perhaps this should also be fired from `s:code_kill`?

**Comment by lervag** [comment]
Just to be more specific, this is what I'm trying to do:

```vim
augroup MyCodi
  autocmd!
  autocmd User CodiEnterPost
        \ hi VertSplit guifg=bg guibg=NONE
        \|hi NonText guifg=bg guibg=NONE
  autocmd User CodiLeavePost
        \ hi clear VertSplit NonText
augroup END
```

The `CodiEnterPost` works fine, the `LeavePost` does not work (and neither does `LeavePre`).

**Comment by metakirby5** [comment]
Reopening for now - I'll check this out when I get the chance :)

**Comment by lervag** [comment]
Thanks!

**Comment by metakirby5** [comment]
@lervag hope this works 🙏

**Comment by lervag** [comment]
Thanks, it seems to work well!
