### ISSUE TITLE
NVim support

### ISSUE THREAD

**Issue by metakirby5** [metakirby5/codi.vim#5]
NVim has a different asynchronous job API, and Codi should support it 😋

**Comment by challsted** [comment]
As a user who uses NVim on all of my devices, I'm super excited for this Issue to be closed :100:

**Comment by ZweiSpeedruns** [comment]
NVim user here. I was wondering why it took 5 seconds to update. Great plugin! Can't wait for async to be fully supported on neovim.

**Comment by metakirby5** [comment]
Note that for the time being, you can set 'updatetime' to something lower in milliseconds to get faster results :)

**Comment by ZweiSpeedruns** [comment]
As expected, the lower I set it, the slower NVim itself runs. This is actually why I switched to neovim in the first place, then vim had to add the async functionality in order to compete.

**Comment by metakirby5** [comment]
I have NVim support working for most languages, but it's not perfect quite yet because there are a few oddities with the stdin/stdout streams (Ocaml in particular is giving me a bit of trouble). However, Vim support should be unaffected (i.e. this commit should introduce no noticeable changes for vim users). Should I push and close, then address any issues with NVim as they arise? I just would like the input of the people who will be using this before I go ahead and push it.

**Comment by metakirby5** [comment]
If anyone wants to give it a spin, the changes are staged in the `user/metakirby5` branch.

I still can't quite figure out NVim's streaming quirks though. Here's what the data I get back looks like:
![nvim](https://www.dropbox.com/s/nl3cjdeu5fbgmki/Screenshot%202016-08-15%2000.03.05.png?dl=1)

It should really look like this though (Vim pictured below):
![vim](https://www.dropbox.com/s/v9du102naxhq32k/Screenshot%202016-08-15%2000.05.38.png?dl=1)

However, in most cases (I haven't done exhaustive testing), both Vim and NVim will more or less display things correctly without raw:
![no-raw](https://www.dropbox.com/s/ypwmqaaeat6y5bg/Screenshot%202016-08-15%2000.07.00.png?dl=1)

The main issue comes from OCaml, which is super inconsistent in printing line breaks and prompts with NVim. However, OCaml isn't a language I've seen a lot of requests for, so I'm leaning on merging this in.

**Comment by balta2ar** [comment]
I'm using neovim and it's working fine on my home machine with ArchLinux where all packages are up to date. However on my working machine with Ubuntu 12.04 nothing is shown in the Codi buffer. How do I diagnose the issue here? (I'm trying python interpreter, tried both python2 and python3 inside miniconda and without it)

**Comment by metakirby5** [comment]
@balta2ar that's interesting... I suspect that the prompt counts are getting messed up, but please try forcing synchronous to confirm this. After pulling `user/metakirby5` again (I fixed a bug where forcing sync wasn't working with nvim), try the following and post screenshots:

- `nvim _.py -c 'let g:codi#sync = 1 | Codi'` 
- `nvim _.py -c 'let g:codi#sync = 1 | let g:codi#raw = 1 | Codi'`

**Comment by balta2ar** [comment]
Nothing is displayed after either of two commands.

Using 0f6229d:
![](http://scrin.org/i/16/08/tmpatfiixcpehs.png)

> `nvim _.py -c 'let g:codi#sync = 1 | Codi'`
![](http://scrin.org/i/16/08/tmpqdzdfgeyqws.png)

> nvim _.py -c 'let g:codi#sync = 1 | let g:codi#raw = 1 | Codi'
![](http://scrin.org/i/16/08/tmpl0engkarsns.png)

**Comment by balta2ar** [comment]
Just to clarify, I also tried entering simple expressions like "1+1" and nothing displayed.

**Comment by iovis9** [comment]
I'm getting synchronous behaviour. Is there a way I could check if my plugin manager is loading the correct branch from inside nvim? Some new variable I can check or something.

**Comment by metakirby5** [comment]
@iovis9 Just go wherever your Vim plugin directory, go into the `codi.vim` directory, and `git checkout user/metakirby5`. I can give you more specific instructions about how to locate your plugin directory if you tell me what manager you're using.

@balta2ar Would you mind telling me the following about your Ubuntu machine?

- What the output of `man script` says (since `script` doesn't have a `--version` flag)
- Whether or not Codi with regular Vim works on the machine
- `python --version`

**Comment by iovis9** [comment]
That's exactly what I did so then I confirm I have synchronous behaviour. 
Nvim 0.1.4

**Comment by metakirby5** [comment]
@iovis9 Did you checkout the branch from `~/.config/nvim/<plugin folder>/codi.vim`, rather than `~/.vim/<plugin folder>/codi.vim`? I made that mistake earlier and it tripped me up, so I just want to rule that out.

**Comment by iovis9** [comment]
I only have `~/.vim/bundle/...` as I have both vim and neovim running under the same configuration.

**Comment by ZweiSpeedruns** [comment]
I would test the branch, but I can't figure out how to use the branch using dein :(

**Comment by metakirby5** [comment]
@ZweiSpeedruns What does the line that says `call dein#begin({path to plugin base path directory})` have? The codi.vim repo is likely within your plugin base path directory. (No guarantees though, since I've never used dein...)

**Comment by bert88sta** [comment]
Is this something that makes use of msgpack?

**Comment by metakirby5** [comment]
@bert88sta Not that I know of... I'm not super familiar with NVim, but I only used its [jobs API](https://neovim.io/doc/user/job_control.html).

**Comment by metakirby5** [comment]
@balta2ar Also, what's your 'updatetime'? It will take that long to show up, and the default iirc is 4 seconds, so perhaps you aren't waiting enough.

**Comment by balta2ar** [comment]
@metakirby5 

My updatetime is:
```
:set updatetime?
  updatetime=1000
Press ENTER or type command to continue
```

script:
```
→ script -V 
script from util-linux 2.20.1
```
man script doesn't show version but it shows "February 2011" in the bottom.

python:
```
→ python --version
Python 2.7.3
```

Codi with regular Vim works on the machine: no, it does not. I've tried this version of vim:
```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Dec  7 2015 16:24:32)
Included patches: 1-963
```

My version of neovim is:
```
NVIM v0.1.5-630-g291c3c6
Build type: Debug
```

**Comment by metakirby5** [comment]
@balta2ar Ah, it looks like my manpage says June 2014. I'm not sure if `script` has had any breaking updates, but could you get a newer version of script to see if this is the case?

In any case, the fact that normal Vim isn't working seems like entirely different issue. If the problem still persists after confirming the issue isn't the `script` version, please open a separate issue for this.

**Comment by balta2ar** [comment]
@metakirby5 Yes indeed, compiling a more recent version of script  from here (https://github.com/karelzak/util-linux) helped! Thank you!
Is there way to use script in a more compatible way?

**Comment by metakirby5** [comment]
@balta2ar Unfortunately, `script` is already a hacky solution by nature. It gets even worse when you take into account that BSD and Linux have entirely different versions of `script`. I've looked into alternatives a bit more, and python's [pty](https://docs.python.org/3.2/library/pty.html) module looks promising. They even have a minimal implementation of `script`! With this, we could remove the `script` dependency and possibly even get Windows support as a bonus. The only downside is the introduction of a `+python` dependency, but considering there are already `+job`, `+channel`, and `script` dependencies, it seems like a worthwhile tradeoff.

**Comment by iovis9** [comment]
Hi, I recently downloaded the last changes and NVIM is now working asynchronously as expected.
If you want me to test something in particular I'm around.

**Comment by metakirby5** [comment]
@iovis9 Great! If you could play around with the different languages (OCaml is giving me a lot of trouble in particular), with different combinations of line breaks, it would be very helpful. Let me know if responsiveness is satisfactory, if any unexpected processes show up and stay running (using `htop` or whatever you like), and just if there's anything out of the ordinary in general.

**Comment by iovis9** [comment]
Well, I have no idea of OCaml but I'll play around :)
I only tested on Python but I'll check which languages the plugin supports and at least try the ones I know.

What would be an example of an unexpected process showing up in my processes? I'm not familiar with what's expected and what not.

**Comment by metakirby5** [comment]
For unexpected processes, let's take Python for example. Let's say you type in `2 + 2` and you see `4` on the right pane - you should expect no `python` or `script` processes to be running. I typically check this using `ps aux | grep python`, but I'm sure there's a better way. Also, processes that have a `Z` in the 8th column are fine; they just haven't been cleared from the process table yet.

If it's too much trouble, you don't need to look at processes - I'm more concerned with overall usability, correctness, and ensuring it won't spin your fans up to 100 degrees 😝

**Comment by iovis9** [comment]
Putting these two lines in python and then hitting enter for newlines creates weird outputs on the right, a different one for each newline.
(NVIM 0.1.4, Python 2.7.12)

![screen shot 2016-08-16 at 12 31 43](https://cloud.githubusercontent.com/assets/6660202/17696258/8a3051a0-63ad-11e6-81ec-88a297c3abea.png)

**Comment by metakirby5** [comment]
Thank you for finding that! I suspected that NVim's funky handling of input would mess with the selection of what to display. If you `let g:codi#raw = 1` and `:CodiUpdate` a few times, you can see that despite the main buffer not changing, the Codi pane inconsistently changes. This will likely be the case for other languages as well, particularly when you get continuation lines without an immediate result.

From a usability standpoint though, what do people think? It appears after my initial testing that statements which actually evaluate (such as string literals) still show up fine, but I will admit it's jarring to have inconsistent output.

**Comment by iovis9** [comment]
I confirm evaluations don't change; but assignments, comments, loops, etc., will show weird output for every keypress. From a usability POV I think it's distracting and not ready yet.

![screen shot 2016-08-16 at 12 50 23](https://cloud.githubusercontent.com/assets/6660202/17696686/5968f150-63b0-11e6-8284-7fe7b9973ddc.png)

**Comment by metakirby5** [comment]
@iovis9 Roger that. I'll look a bit further into using Python's `pty` module. For the time being, NVim users can keep using the `user/metakirby5` branch for experimental support.

**Comment by fwalch** [comment]
@metakirby5 Not that I really understand the problem, but you could try to also open an issue at https://github.com/neovim/neovim to see if the problems can somehow be solved.

**Comment by metakirby5** [comment]
@fwalch Good suggestion. If `pty

**Comment by still-dreaming-1** [comment]
If you are interested in making this a remote plugin for Neovim support instead of using the job control, I might be able to help. I don't know if doing that makes sense for this type of plugin, but I am under the impression it tends to be considered a better way to make plugins. I am currently working on rewriting my project-tags plugin to be written in JavaScript / Node.js, so I am learning about making remote plugins. As far as developing plugins this way, its seems they basically provide tie ins to do certain things: Create autocmds, create mappings, run VimL functions, create VimL functions, run VimL commands, define VimL commands. When I create autocmds, I write what JavaScript code runs when they get triggered. When I define a VimL function, I mean VimL is aware of this function, but I write JavaScript code that Node runs when the function gets called. When you define a VimL command, the command is available as a standard VimL command, but I write the JavaScript code that Node runs whenever that command is executed. I am using [node-host](https://github.com/neovim/node-host) to do all this.

**Comment by metakirby5** [comment]
@still-dreaming-1, I would like to keep project dependencies to a minimum - is that still possible with remote plugins?

In other news: I noticed a way to get NVim's async output to behave more like Vim's, and it seems to be working quite well. I've pushed the update to `user/metakirby5`. It seems to eliminate the weird output @iovis9 was mentioning. Everyone, please test when you get the chance!

**Comment by still-dreaming-1** [comment]
@metakirby5 It would probably add a dependency on whatever is needed to run the code in whatever language you wanted to write the plugin in. Depending on python is pretty standard though, if you wanted to write the plugin in python. Also users have to run `:UpdateRemotePlugins` inside Neovim after they install or update the plugin.

**Comment by still-dreaming-1** [comment]
I just tested it on `user/metakirby5`. I was already on that branch, and prior to the latest updates it was partially working with node. Now it doesn't work at all for me. I will try going back some commits and see where it changed...

**Comment by metakirby5** [comment]
@still-dreaming-1 Thank you for the detailed response. However, I disagree with you on one point - maintainability. If I'm not mistaken, remote plugins are only supported by Neovim. This would essentially fragment my codebase into a Vim implementation and an NVim implementation, which is undesirable. At the moment, I've created an adapter for both Vim's and NVim's job API's so they can cleanly share most of the asynchronous logic. If anything, I would instead use Vim and NVim's native python capabilities.

**Comment by still-dreaming-1** [comment]
Yes if you can have a small amount of VimL code that works in both that would be better.

**Comment by metakirby5** [comment]
Regarding the branch not working - what OS are you running? I've only tested it on OS X, as I don't currently have access to my Ubuntu VM. My suspicion is that it breaks because of the differences in `script` behavior between BSD and Linux.

**Comment by still-dreaming-1** [comment]
I'm on Linux Mint 17.3 which is based on Ubuntu 14.04 which is based on Debian.

**Comment by still-dreaming-1** [comment]
Commit `4757f976e5347b2963930df54ba11bad4e8ba28a` also does not work at all for me. `ce63b51244635c8168a90b00392e7b3bf37a11b2` partly works for me. The scratch buffer shows stuff, but it is kind of funky in a way that reminds me of the problems described above. It is different from what Vim shows.

**Comment by metakirby5** [comment]
@still-dreaming-1 Strange, it seems to work for me. What version of `script` do you have? Since you're on Linux, `script --version` should tell you.

**Comment by justinmk** [comment]
Did you try the `pty` option of nvim's `jobstart`?

**Comment by metakirby5** [comment]
@justinmk `jobstart` has a `pty` option? I can't seem to find it in the [documentation](https://neovim.io/doc/user/job_control.html), is there a different document I should be looking at?

**Comment by justinmk** [comment]
See `help jobstart`. It runs an actual (pseudo) terminal in the job. It may avoid the need for `script` entirely, including on Windows when we merge support for winpty.

**Comment by justinmk** [comment]
Use `jobsend` to send keys to the pty spawned by `jobstart`.

**Comment by metakirby5** [comment]
@justinmk OMG, that's a game changer. It looks like things are working really well with it. I'll play around with it some more before pushing up a change to my branch.

**Comment by metakirby5** [comment]
@justinmk @still-dreaming-1 @iovis9 would you mind giving the latest commit a go?

**Comment by iovis9** [comment]
You got the attention of the neovim team haha. I'll check out the changes :)

**Comment by iovis9** [comment]
Testing against 64279c163fd7ddcae938aae534774e80641dc196 and NVIM v0.1.5-762-gdfb6a51.

The plugin "feels" better in performance, output issues not solved.
![screen shot 2016-08-18 at 10 50 52](https://cloud.githubusercontent.com/assets/6660202/17767781/afa64d56-6531-11e6-8d25-2fe8505f050f.png)

**Comment by metakirby5** [comment]
Thanks for testing it out! It's so weird that you and I have nearly the same setup, but I can't reproduce the output issue on my machine after the latest commits. It appears to work just as well as the Vim version both on my OS X machine and my Ubuntu VM. Can you double-check if you have the changes introduced by 4757f976e5347b2963930df54ba11bad4e8ba28a?

**Comment by iovis9** [comment]
Huh. I doubled checked and, sure enough, I had the changes. Tested again just in case and all the weird output disappeared... 😕

**Comment by still-dreaming-1** [comment]
It's working! :D This is the coolest plugin I have seen in a while. Just recently I have been really wanting something like this. So recently a couple of my dreams have come true. The code from the file I'm writing in can be run through a REPL as I write it in the file, I can run a browser inside my editor if I use NyaoVim... I wonder what will happen next! BTW, codi works in NyaoVim too! Not that there is any reason it shouldn't, but I'm happy because I may switch to that editor full time. I wonder if I could get the REPL to show the results of each test in a unit test file just by opening codi in it... I'm sure either the tests or Codi would have to be setup a certain way... But if that could happen, it would just be incredible. I could edit the tests and see them change to passing or failing as I'm writing them.

**Comment by balta2ar** [comment]
@still-dreaming-1 I'm curious to see your workflow in NyaoVim + Codi. Could you share a short movie demonstrating how you use them together, maybe as gif? In fact, I'm more interested in NyaoVim because I'm already using Codi myself. Thanks!

**Comment by still-dreaming-1** [comment]
@balta2ar I'm still just experimenting with them at this point. But you can checkout some videos and watch me code live here: https://www.livecoding.tv/still_dreaming_1/
Nothing that shows off anything good with NyaoVim or Codi yet.

**Comment by hoschi** [comment]
For me the output is cutted in NeoVim (terminal UI), I see "undef" instead of "undefined" for an JS example.

**Comment by metakirby5** [comment]
@hoschi can you post a screenshot and/or screencast, OS, `script` version, and Vim version?

**Comment by still-dreaming-1** [comment]
My editor also has some quirky behavior when running codi. It goes back to normal when I close the scratch buffer. If I press d twice to delete a line, and do this repeatedly, it will start deleting a line with each d press instead of requiring 2. This only happens if I press d fast enough. Sometimes V will go into and out of visual mode with a single keypress.

**Comment by hoschi** [comment]
@metakirby5
Here you see the state after `:Codi` with the cutted text on the right side:
![2016-08-19-100056_986x633_scrot](https://cloud.githubusercontent.com/assets/163128/17803018/eb340094-65f3-11e6-9da7-ed1f1f9d9b1d.png)

Here I dragged the splitter to the left, to show it evaluates the code:
![2016-08-19-100109_986x633_scrot](https://cloud.githubusercontent.com/assets/163128/17803044/0df782fe-65f4-11e6-8c44-bcf1882a6db3.png)

NVIM v0.1.5-630-g291c3c6
OS: Arch Linux, updated 29 days ago
scrupt: script from util-linux 2.28

**Comment by metakirby5** [comment]
@still-dreaming-1 Would you mind telling me all the details to reproduce the issue? e.g. filetype used, exact buffer contents, location of cursor prior to actions, keystrokes to reproduce bug, etc.

@hoschi Did you need to resize the buffer at all to reproduce the issue? Also, can you run Codi with `nvim -c 'let g:codi#rightalign = 0 | Codi` _.js`? That should left-align the Codi buffer; I just want to see if that's the only issue.

**Comment by iovis9** [comment]
@hoschi I can't reproduce the issue.
![screen shot 2016-08-19 at 22 13 04](https://cloud.githubusercontent.com/assets/6660202/17822945/434e1786-665a-11e6-8a20-7c1edc9ee4e6.png)

NVIM v0.1.5-762-gdfb6a51
OS X 10.11.6

**Comment by still-dreaming-1** [comment]
I'm having trouble coming up with an exact reproduce case, but I will keep working on that. For now I can tell you I am working with .js files, so node is the REPL. For most .js files that I open, if I move the cursor partway down the file, and then press d fast enough, eventually every keystroke deletes a line instead of every 2 keystrokes.

**Comment by still-dreaming-1** [comment]
Here is a good reproduce, just place this in a .js file:
```
assert(true)
assert(true)
assert(true)
assert(true)
assert(true)
assert(true)
assert(true)
assert(true)
assert(true)
assert(true)
assert(true)
assert(true)
assert(true)
assert(true)
assert(true)
assert(true)
assert(true)
assert(true)
assert(true)
assert(true)
assert(true)
assert(true)
assert(true)
assert(true)
assert(true)
assert(true)
assert(true)
assert(true)
assert(true)
```

Move the cursor down to line 8. If you repeatedly press d fast enough, eventually every keystroke will delete a line instead of every other keystroke. I will keep working on narrowing this down more by disabling all my plugins and mappings and see if I still have this issue.

**Comment by still-dreaming-1** [comment]
I have confirmed I have this issue and that reproduce works when the only thing in my config is enabling the codi.vim plugin. I'm on NVIM 0.1.5-dev. I used the Ubuntu ppa mentioned here to install Neovim: https://github.com/neovim/neovim/wiki/Installing-Neovim

My `script --version` says `script from util-linux 2.20.1`

**Comment by metakirby5** [comment]
@still-dreaming-1 I was able to reproduce it on my machine - I'll take a look.

**Comment by hoschi** [comment]
@iovis9 
I debugged my config and found the problem:
```
" Use relativenumber only in the focused window
if exists('&relativenumber')
  set relativenumber
  augroup WindowRNU
    auto!
    auto BufWinEnter,WinEnter,FocusGained * setlocal relativenumber
    auto WinLeave,FocusLost               * setlocal number
  augroup END
endif
```

**Comment by still-dreaming-1** [comment]
It seems now that Neovim support is partly working, mabye these could be turned into separate issues. It seems like this is becoming a place to get help for any Neovim issue. I can make mine a separate issue if you want? Maybe this branch is ready to merge into master if it will not cause issues in regular Vim?

**Comment by challsted** [comment]
@still-dreaming-1 :+1: i like that idea, seperate it out into actual issues instead of just just an umbrella

**Comment by metakirby5** [comment]
Good idea - better to resolve the NVim issues one by one instead of in one big thread. After I make some documentation changes I'll merge it in.

**Comment by metakirby5** [comment]
Merged! Please re-open outstanding issues individually :)

**Comment by justinmk** [comment]
So `script` is not needed with nvim, correct? Might want to mention that in the readme/doc.

**Comment by metakirby5** [comment]
@justinmk Good catch - will mention that.
