### ISSUE TITLE
Typing "subprocess" in python locks out the user

### ISSUE THREAD

**Issue by vatrat** [metakirby5/codi.vim#55]
I'm using Neovim. When in python mode, I type:
```
import subprocess

subprocess
```

Then, I stop being able to type as soon as I finish "subprocess." The cursor still blinks, so it's still running, but something is stopping me from typing, presumably a subprocess. Honestly, I find this bug quite funny. I laughed when it first happened.

**Comment by metakirby5** [comment]
That's pretty funny! I can't seem to reproduce this, unfortunately...

![](https://www.dropbox.com/s/yn07qq5d5hzw5jv/Screenshot%202016-12-15%2021.25.48.png?dl=1)

This only happens with subprocess?

**Comment by vatrat** [comment]
Whoops, this is actually just deocomplete-jedi's suggestions taking a ridiculous amount of time to load on certain words such as subproces. This should be closed.
