### ISSUE TITLE
cannot work on some (not BSD) Linux?

### ISSUE THREAD

**Issue by cympfh** [metakirby5/codi.vim#60]
## Issue description

On my some environments (Ubuntu, CentOS), the `script` command works wrong by the codi.vim's call.

## Environment

```bash
$ uname -vpo
#57-Ubuntu SMP Tue Sep 6 15:42:33 UTC 2016 x86_64 GNU/Linux

$ script --version
script from util-linux 2.27.1

$ script -feqc python -q /dev/null  # Codi.vim call
-c: can't open input file: python

$ echo python -q >/tmp/cmd && script -feqc /tmp/cmd /dev/null
>>> 0
0
>>> 
```

this is my commit to resolve the problem:
https://github.com/cympfh/codi.vim/commit/7cdf9ad36d71007c5d01932948faf521018b6714

**Comment by metakirby5** [comment]
Thanks for reporting this and finding a solution! Would you mind resubmitting this as a PR?

As a side note: `python2` doesn't seem to have a `-q` flag - is this necessary for the fix?

**Comment by cympfh** [comment]
okay.
