### ISSUE TITLE
PHP - Don't pass first line in buffer to PsySH if the line is <?php

### ISSUE THREAD

**Issue by still-dreaming-1** [metakirby5/codi.vim#67]
A PHP code file typically start with `<?php` as the first line. PsySH is not expecting this because php has already started. Therefore, the first bit of output from codi for that line is `PHP Parse error: Syntax error, unexepcted '<' on line 1`. Does codi have any existing features that could be used to alter the buffer content input before it gets sent to the REPL? I would like to simply not send that line to PsySH if that exact string is the first line in the buffer. if such a feature does not yet exist in codi, I may try to add it, but I wanted to get your input first.

**Comment by metakirby5** [comment]
Thanks for reporting this! You should be able to achieve the desired fix with [`rephrase`](https://github.com/metakirby5/codi.vim/blob/master/doc/codi.txt#L521). Let me know if you have any further questions.
