### ISSUE TITLE
JavaScript object doesn't output

### ISSUE THREAD

**Issue by xahon** [metakirby5/codi.vim#73]
![image](https://user-images.githubusercontent.com/18731681/29250654-b2481b10-8089-11e7-8c59-01dca8f2f1ad.png)

Also it's not working with `JSON.stringify(object)`
Codi works well, see my previous issue #72.

**Comment by rijkvanzanten** [comment]
The code you demo in the screenshot isn't valid which is probably why it doesn't show.

You can try this for yourself by trying to run the code in a browser console

```javascript
let mock = {[
  {id: 1},
  {id: 2, parent: 1},
  {id: 3, parent: 2},
  {id: 4, parent: 5},
  {id: 5, parent: 3}
]};

mock;
// -> SyntaxError: Unexpected token ','. Expected ']' to end a computed property name.
```

**Comment by xahon** [comment]
@rijkvanzanten yes, i understood that. Key is needed
