### ISSUE TITLE
[Feature request] Support windows

### ISSUE THREAD

**Issue by ghost** [metakirby5/codi.vim#77]
If you only have a quick question, consider posting it on the Gitter.

Otherwise, please include the following:

## Issue description
- Brief description
- Expected results
- Actual results
- A minimal `.vimrc` that will reproduce the issue
- Exact steps to reproduce the issue, starting with the command used to open
  `vim`
- Any relevant screenshots
- If it's not too much trouble, a screencast (e.g. asciinema) of the issue

## Environment
- Operating system
- Version of `script` (if you don't know, just paste the last line of the
  man page)
- The following **in a pastebin**, to reduce visual clutter:
  - Entire output of `vim --version`
  - Log lines (see `:h g:codi#log`)

I don't know how many windows user like me but if possible please add this feature.

**Comment by zfoell** [comment]
Looks like a great plugin! Still no support for Windows?

**Comment by siqueira-gustavo** [comment]
Still nothing in Aug 2022

**Comment by metakirby5** [comment]
Happy to take a pull request for it.

**Comment by metakirby5** [comment]
Should be working with #158 now, please give it a try!

cc @Jacesheck
