### ISSUE TITLE
No Codi interpreter for python

### ISSUE THREAD

**Issue by anoopd** [metakirby5/codi.vim#80]
When i try to do Codi {python} i am getting the error

Error detected while processing function codi#run:
line   21:
E474: Invalid argument: filetype={python}
No Codi interpreter for {python}.
Press ENTER or type command to continue

Can somebody help me  ...... i have all the dependencies installed

**Comment by metakirby5** [comment]
In vim doc format, braces indicate an argument. So, you should actually run `Codi python`.
