### ISSUE TITLE
How to make it working with python3

### ISSUE THREAD

**Issue by anoopd** [metakirby5/codi.vim#81]
I have both python2 and python3 installed in my OS X . python 2 is called with `python` keyword and python3 with `python3` keyword . Codi does not recognize python3 packages (like pymysql ) . it is showing  `Importerror` , but the script works fine  . Is there a way to make it work with python3.

**Comment by metakirby5** [comment]
Please refer to the [documentation for defining custom interpreters](https://github.com/metakirby5/codi.vim/blob/0c5653fc36fb328c1ca3c3a62ed98ec15cb6d4c1/doc/codi.txt#L182).

Going forward, if you only have a quick question, please post it on the [Gitter](https://gitter.im/codi-vim/Lobby). I'd like for issues to be reserved for bugs and feature requests.
