### ISSUE TITLE
Errors on start up with javascript

### ISSUE THREAD

**Issue by andythedandyone** [metakirby5/codi.vim#82]
Kubuntu 16.04
Vim 7.4

when starting `Codi javascript` it returns the errors below:
![image](https://user-images.githubusercontent.com/20182536/38910174-1e14dce2-4296-11e8-8ab3-99b1ccd8903e.png)

then after pressing enter, it opens the right pane, with a result at the top but when adding more functions, it shows nothing:
![image](https://user-images.githubusercontent.com/20182536/38910215-4f82cd20-4296-11e8-88a5-cbfbd015b40e.png)

**Comment by metakirby5** [comment]
Try updating - does it work now?

**Comment by andythedandyone** [comment]
Yep, I updated to 8.0 few minutes after and it worked.
So, I take that v7 is not compatible, it had channel and jobs, but I think the async is not avail in v7's.

**Comment by andythedandyone** [comment]
That would explain vim v7.xx complained when I tried to `set signcolumn=yes`
