### ISSUE TITLE
Codi creating hundreds of .python_history-12345.tmp files

### ISSUE THREAD

**Issue by lukelbd** [metakirby5/codi.vim#85]
When I use Codi in a `.py` file, several hidden files are created in my home directory every time a new output in the left-panel is generated; usually 3 or so. They all look like this

    .python_history-12345.tmp

but replace the 12345 by any 5 numbers. They can add up to hundreds of files over time.

What is going on/how can I prevent this, or at least how can I have Codi delete them automatically when a new calculation is completed?

**Comment by metakirby5** [comment]
We can probably [disable the history feature](https://unix.stackexchange.com/questions/121377/how-can-i-disable-the-new-history-feature-in-python-3-4) in a [preprocess](https://github.com/metakirby5/codi.vim/blob/master/doc/codi.txt#L493). I currently don't have time to work on this, but am happy to merge in a fix for it.

**Comment by lukelbd** [comment]
As a work around, is there any way I can revert to an older version of python without the history feature (e.g. use `python2` for the `python` interpreter)?

**Comment by metakirby5** [comment]
Yes; please see the [example interpeter configuration](https://github.com/metakirby5/codi.vim/blob/master/doc/codi.txt#L456).

**Comment by lukelbd** [comment]
+1 year later I figured out a crude way to fix this -- just take advantage of the `'quitcmd'` interpreter option as follows

```vim
let g:codi#interpreters = {
    \ 'python': {
        \ 'bin': 'python',
        \ 'prompt': '^\(>>>\|\.\.\.\) ',
        \ 'quitcmd': "import readline; readline.clear_history(); exit()",
        \ },
    \ }
```

This clears the history file every time codi closes an interactive prompt. This also means that if you tend to use interactive `python` prompts in another terminal, the history from those inputs will be deleted every time you use `codi`.

**Comment by lukelbd** [comment]
Think I'll close this. Despite the drawbacks of the above solution, it's probably the best option. Not sure it is even [possible](https://unix.stackexchange.com/questions/121377/how-can-i-disable-the-new-history-feature-in-python-3-4) to suppress history for a particular interactive `python` session.

**Comment by lukelbd** [comment]
Another 2 years later, this works much better (adapted from [this solution](https://unix.stackexchange.com/a/436571/112647) from the stackoverflow thread):

```vim
let g:codi#interpreters = {
    \ 'python': {
        \ 'bin': ['python3', '-i', '-c', "'import readline; readline.set_auto_history(False)'"],
        \ 'prompt': '^\(>>>\|\.\.\.\) ',
        \ 'quitcmd': 'exit()',
    \ }
```
