### ISSUE TITLE
Neovim , windows with script.exe (Cygwin) bug .

### ISSUE THREAD

**Issue by upgradeQ** [metakirby5/codi.vim#86]
## Issue description
- Neovim evaluates only one line like in this [issue](https://github.com/metakirby5/codi.vim/issues/46#issue-181083461) 
- Expected results - fully functional codi.vim instance 
- Actual results - Codi evaluates only one line .
- Exact steps to reproduce the issue, starting with the command used to open:
    `nevim-qt ` -> ` :e codi_screen_cast.py `  -> `:Codi  `
- Any relevant screenshots
<details><summary> screenshot with one line  </summary><p>

![one_line_only](https://user-images.githubusercontent.com/18361586/39889594-097a4124-54a1-11e8-91a9-9a57dade4203.gif)
</p></details>
<details><summary> screenshot with python version  </summary><p>

![python_from_path](https://user-images.githubusercontent.com/18361586/39889608-1293e1ac-54a1-11e8-97b1-24d2ca392f93.gif)
</p></details>

## Environment
- Windows 7 
- script from util-linux 2.25.2
:v:

**Comment by pranavpa8788** [comment]
Isn't codi not supported for Windows yet? How did you get it to work?

**Comment by metakirby5** [comment]
Should be working with #158 now, please give it a try!

cc @Jacesheck
