### ISSUE TITLE
Can it surpport HerringtonDarkholme/typescript-repl ?

### ISSUE THREAD

**Issue by hackingcat** [metakirby5/codi.vim#87]
If you only have a quick question, consider posting it on the Gitter.

Otherwise, please include the following:

## Issue description
- Brief description
- Expected results
- Actual results
- A minimal `.vimrc` that will reproduce the issue
- Exact steps to reproduce the issue, starting with the command used to open
  `vim`
- Any relevant screenshots
- If it's not too much trouble, a screencast (e.g. asciinema) of the issue

## Environment
- Operating system
- Version of `script` (if you don't know, just paste the last line of the
  man page)
- The following **in a pastebin**, to reduce visual clutter:
  - Entire output of `vim --version`
  - Log lines (see `:h g:codi#log`)

**Comment by metakirby5** [comment]
Probably. Please see [the interpreters section of the docs](https://github.com/metakirby5/codi.vim/blob/master/doc/codi.txt#L332) for details. Check out a [the PR for Lua support](https://github.com/metakirby5/codi.vim/pull/40/files) for an example.

**Comment by pittcat** [comment]
Solved,thank you.

**Comment by metakirby5** [comment]
Excellent! If you have time, please feel free to make a pull request so others can benefit from your work 😄
