### ISSUE TITLE
Can't print string with '\n' in python

### ISSUE THREAD

**Issue by dylan-chong** [metakirby5/codi.vim#89]
If you only have a quick question, consider posting it on the Gitter.

Otherwise, please include the following:

## Issue description
- Brief description - Trying to string with multiple lines
- Expected results - when i try to print the string with the `\n`s in it, all of the lines should be shown
- Actual results - when i try to print the string with the `\n`s in it, only the last line is shown
- A minimal `.vimrc` that will reproduce the issue - Hopefully this isn't actually needed i will supply this if needed
- Exact steps to reproduce te issue, starting with the command used to open
  `vim`
    1. Open codi while in a python file
    2. Type a string with multiple lines for example `print 'a\nb'`. You will only see the last line in the output
- Any relevant screenshots ![screen shot 2018-06-30 at 10 51 29 pm](https://user-images.githubusercontent.com/17482349/42124524-26e4e48c-7cb8-11e8-9753-875fa3325588.png) 
![screen shot 2018-07-01 at 10 07 39 am](https://user-images.githubusercontent.com/17482349/42129352-9ed6457c-7d16-11e8-8dd7-22aac10aeb2e.png)

- If it's not too much trouble, a screencast (e.g. asciinema) of the issue - Hopefully not needed

## Environment
- Operating system   - mac 10.13.5 (17F77)
- Version of `script` (if you don't know, just paste the last line of the
  man page)
- The following **in a pastebin**, to reduce visual clutter: https://pastebin.com/pk9FNcTt
  - Entire output of `vim --version`
  - Log lines (see `:h g:codi#log`)

**Comment by dylan-chong** [comment]
What I'm essentially trying to do in the above example is generate a list of test cases to pass into my function. I'm not sure if this is a valid use case of this plug-in, but would be useful nonetheless.

Another possible use case is you want to generate an output with multiple lines, for example pretty printed Json. If you could only see the last line of the Json, it would be not very useful

---


I am wondering about whether showing the result side-by-side for each line is actually possible, since showing a multiple line output would shift the results below. I'm sure you are aware of this

Another problem is where a string or some output is too long and so wraps onto a new line.

![screen shot 2018-07-01 at 10 11 33 am](https://user-images.githubusercontent.com/17482349/42129399-976dccdc-7d17-11e8-806e-5c079a1fe17f.png)

**Comment by dylan-chong** [comment]
I intentionally turned off no wrap because I wanted to see the rest of the output

**Comment by metakirby5** [comment]
I see. Everything is working as intended, then; I think you'll have to pursue another way to achieve your desired result, because Codi isn't built for this use case.

**Comment by dylan-chong** [comment]
Just a thought, what about showing all lines of output for the last line?
