### ISSUE TITLE
[Feature Request] Elm Support

### ISSUE THREAD

**Issue by midnio** [metakirby5/codi.vim#93]
There is `elm repl` to use elm's repl. I think that will be fine if you add Elm support :smiley:

**Comment by metakirby5** [comment]
Done in fad76cc, enjoy!

<img width="1042" alt="screen shot 2018-08-18 at 22 53 07" src="https://user-images.githubusercontent.com/3402603/44305995-5a1bc480-a33a-11e8-9c7b-4049d5c0d89e.png">

**Comment by midnio** [comment]
Thanks!
