### ISSUE TITLE
bash support?

### ISSUE THREAD

**Issue by qiufeihai** [metakirby5/codi.vim#99]
bash support?

**Comment by metakirby5** [comment]
There is no intention to add built-in support for bash for the following reasons:

- Many users like to customize their prompt, and prompts even vary across linux distributions. Codi is reliant on regex matching the prompt to detect the next line of output, so the implementation will likely only work on a small subset of machines at any given time.
- Codi constantly evaluates your input. A command line shell is a dangerous thing to play with, and I don't want to be responsible for the person that accidentally types in `rm -rf ~`.

If you would like to have bash support yourself, please refer to [the documentation for the `g:codi#interpreters` setting](https://github.com/metakirby5/codi.vim/blob/master/doc/codi.txt#L183).

**Comment by qiufeihai** [comment]
let g:codi#interpreters = {
 \ 'bash': {
          \ 'bin': ['bash'],
          \ 'prompt': '^\(>\|\.\.\.\+\) ',
          \ }

and 

let g:codi#raw=1

but  not working , input is empty
